import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/assets/globals.css";
import Header from "@/app/components/header/index";
import Navbar from "@/app/components/navbar/index";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <Navbar />
          <div className="flex flex-col w-full">
            <Header />
            <main className="flex-1 bg-[#e4e4e4] p-5">{children}</main>
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
